/* ============================================================
   admin.js — لوحة التحكم · BE-P3
   وضعان يُكتشفان تلقائياً:
   LIVE  → حارس دخول (أدمن فقط) + كل البيانات والحفظ من قاعدة D1
   DEMO  → البيانات التجريبية من admin-data.js (قبل تجهيز القاعدة)
   ============================================================ */

var adminState = { theme: 'light', view: 'overview', selectedTask: null };
var ADMIN_LIVE = false;
var L_TASKS = [];     /* المهام (نموذج المحرر الموحّد) */
var L_EMPS = [];      /* الموظفون */
var L_OUTS = [];      /* المخرجات */

var ROLE_LIST = ['reception', 'marketing', 'social', 'website', 'stores', 'hr', 'accounting'];

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/* ================= Navigation ================= */
var VIEW_TITLES = {
  overview: 'نظرة عامة',
  tasks: 'المهام والـ Schemas',
  employees: 'الموظفون والأقسام',
  review: 'مراجعة المخرجات',
  mindfiles: 'ملفات العقول (منظومة العقول)'
};

function switchView(view) {
  adminState.view = view;
  var navs = document.querySelectorAll('.nav-item');
  for (var i = 0; i < navs.length; i++) {
    navs[i].classList.toggle('active', navs[i].getAttribute('data-view') === view);
  }
  var views = document.querySelectorAll('.admin-view');
  for (var j = 0; j < views.length; j++) {
    views[j].classList.toggle('active', views[j].id === 'view-' + view);
  }
  document.getElementById('viewTitle').textContent = VIEW_TITLES[view];
}

/* ================= Theme ================= */
function toggleTheme() {
  adminState.theme = (adminState.theme === 'light') ? 'dark' : 'light';
  document.body.setAttribute('data-theme', adminState.theme);
  document.getElementById('themeBtn').textContent = (adminState.theme === 'light') ? '🌙' : '☀️';
}

/* ============================================================
   تحويل مهمة القاعدة ⇄ نموذج المحرر
   ============================================================ */
function dbTaskToEditor(t) {
  var p = t.payload;
  return {
    id: t.id,
    icon: p.icon || '🆕',
    name: (p.ar && p.ar[0]) || t.id,
    role: t.role,
    enabled: t.enabled,
    instructions: t.instructions || '',
    fields: (p.fields || []).map(function (f) { return { label: f.ar, type: f.type }; }),
    payload: p
  };
}

function editorToPayload(task) {
  var p = task.payload || {
    icon: '🆕',
    ar: [task.name, 'مهمة جديدة'],
    en: [task.name, 'New task'],
    steps: task.fields.length,
    fields: [],
    result: {
      ar: 'تم استلام البيانات — المخرَج يولده المساعد الذكي وفق تعليمات الإدارة.',
      en: 'Data received — the output is generated by the assistant per management instructions.'
    }
  };
  p.icon = task.icon;
  p.ar = p.ar || [task.name, '']; p.ar[0] = task.name;
  p.en = p.en || [task.name, ''];
  p.steps = task.fields.length;

  var oldFields = p.fields || [];
  p.fields = task.fields.map(function (f, i) {
    var old = oldFields[i];
    if (old && old.type === f.type) {
      old.ar = f.label;
      if (!old.en) old.en = f.label;
      return old;
    }
    var nf = { k: 'f' + (i + 1) + '_' + Math.random().toString(36).slice(2, 6), ar: f.label, en: f.label, type: f.type };
    if (f.type === 'select') {
      nf.opts = (old && old.opts) || { ar: ['اختر...', 'خيار 1', 'خيار 2'], en: ['Choose...', 'Option 1', 'Option 2'] };
    }
    return nf;
  });
  return p;
}

/* ================= Overview ================= */
function renderActivity() {
  var list = document.getElementById('activityList');
  list.innerHTML = '';
  if (ADMIN_LIVE) {
    list.innerHTML = '<div class="activity-item">📒 سجل النشاط التفصيلي — في تحديث قادم</div>';
    return;
  }
  for (var i = 0; i < ACTIVITY.length; i++) {
    var a = ACTIVITY[i];
    var el = document.createElement('div');
    el.className = 'activity-item';
    el.innerHTML = '<span>' + a.icon + '</span><span>' + a.text + '</span><small>' + a.time + '</small>';
    list.appendChild(el);
  }
}

function renderStats() {
  var tasks = ADMIN_LIVE ? L_TASKS : ADMIN_TASKS;
  var emps = ADMIN_LIVE ? L_EMPS : EMPLOYEES;
  var enabledCount = 0;
  for (var i = 0; i < tasks.length; i++) if (tasks[i].enabled) enabledCount++;

  var st = document.getElementById('statTasks');
  var sr = document.getElementById('statRoles');
  var se = document.getElementById('statEmps');
  if (st) st.textContent = enabledCount;
  if (sr) sr.textContent = ROLE_LIST.length;
  if (se) se.textContent = emps.length;
}

/* ================= Tasks & Schema builder ================= */
function currentTasks() { return ADMIN_LIVE ? L_TASKS : ADMIN_TASKS; }

function renderTaskList() {
  var list = document.getElementById('adminTaskList');
  list.innerHTML = '';
  var tasks = currentTasks();
  for (var i = 0; i < tasks.length; i++) {
    (function (task, idx) {
      var el = document.createElement('div');
      el.className = 't-item' + (task.enabled ? '' : ' off') + (adminState.selectedTask === idx ? ' active' : '');
      el.innerHTML = '<span>' + task.icon + '</span><span>' + esc(task.name) + '</span><span class="t-role">' + (ROLES[task.role] || task.role) + '</span>';
      el.onclick = function () { selectTask(idx); };
      list.appendChild(el);
    })(tasks[i], i);
  }
}

function selectTask(idx) {
  adminState.selectedTask = idx;
  renderTaskList();
  var task = currentTasks()[idx];
  document.getElementById('builderEmpty').style.display = 'none';
  document.getElementById('builderForm').style.display = 'block';
  document.getElementById('bName').value = task.name;
  document.getElementById('bIcon').value = task.icon;
  document.getElementById('bRole').value = task.role;
  document.getElementById('bInstructions').value = task.instructions;
  document.getElementById('disableTaskBtn').textContent = task.enabled ? 'تعطيل المهمة' : 'تفعيل المهمة';
  renderFields(task);
  renderPreview(task);
}

function renderFields(task) {
  var wrap = document.getElementById('fieldsList');
  wrap.innerHTML = '';
  for (var i = 0; i < task.fields.length; i++) {
    (function (f, idx) {
      var row = document.createElement('div');
      row.className = 'f-row';

      var inp = document.createElement('input');
      inp.type = 'text';
      inp.value = f.label;
      inp.addEventListener('input', function () { f.label = inp.value; renderPreview(task); });

      var sel = document.createElement('select');
      var types = [['text', 'نص قصير'], ['textarea', 'نص طويل'], ['select', 'قائمة اختيار']];
      for (var t = 0; t < types.length; t++) {
        var op = document.createElement('option');
        op.value = types[t][0];
        op.textContent = types[t][1];
        sel.appendChild(op);
      }
      sel.value = f.type;
      sel.addEventListener('change', function () { f.type = sel.value; renderPreview(task); });

      var del = document.createElement('button');
      del.className = 'f-del';
      del.textContent = '✕';
      del.title = 'حذف الحقل';
      del.onclick = function () {
        task.fields.splice(idx, 1);
        renderFields(task);
        renderPreview(task);
      };

      row.appendChild(inp);
      row.appendChild(sel);
      row.appendChild(del);
      wrap.appendChild(row);
    })(task.fields[i], i);
  }
}

function addField() {
  if (adminState.selectedTask === null) return;
  var task = currentTasks()[adminState.selectedTask];
  task.fields.push({ label: 'حقل جديد', type: 'text' });
  renderFields(task);
  renderPreview(task);
}

function saveTask() {
  if (adminState.selectedTask === null) return;
  var task = currentTasks()[adminState.selectedTask];
  task.name = document.getElementById('bName').value.trim() || task.name;
  task.icon = document.getElementById('bIcon').value.trim() || task.icon;
  task.role = document.getElementById('bRole').value;
  task.instructions = document.getElementById('bInstructions').value;

  var btn = document.getElementById('saveTaskBtn');

  if (ADMIN_LIVE) {
    if (!task.fields.length) { alert('أضف حقلاً واحداً على الأقل'); return; }
    btn.disabled = true; btn.textContent = 'جارٍ الحفظ...';
    var payload = editorToPayload(task);
    fetch('/api/admin-tasks', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'save', id: task.id, role: task.role,
        enabled: task.enabled, instructions: task.instructions, payload: payload
      })
    })
      .then(function (r) { return r.json(); })
      .then(function (d) {
        btn.disabled = false;
        if (d.ok) {
          task.payload = payload;
          btn.textContent = '✔ حُفظ في قاعدة البيانات';
          renderTaskList(); renderPreview(task); renderStats();
        } else {
          btn.textContent = 'حفظ';
          alert('خطأ في الحفظ: ' + d.error);
        }
        setTimeout(function () { btn.textContent = 'حفظ'; }, 1800);
      })
      .catch(function () { btn.disabled = false; btn.textContent = 'حفظ'; alert('تعذر الاتصال بالخادم'); });
    return;
  }

  renderTaskList();
  renderPreview(task);
  btn.textContent = '✔ حُفظ (في الذاكرة فقط)';
  setTimeout(function () { btn.textContent = 'حفظ (تجريبي)'; }, 1600);
}

function toggleTaskEnabled() {
  if (adminState.selectedTask === null) return;
  var task = currentTasks()[adminState.selectedTask];
  task.enabled = !task.enabled;
  document.getElementById('disableTaskBtn').textContent = task.enabled ? 'تعطيل المهمة' : 'تفعيل المهمة';

  if (ADMIN_LIVE) {
    fetch('/api/admin-tasks', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'toggle', id: task.id, enabled: task.enabled })
    });
  }
  renderTaskList();
  renderStats();
}

function newTask() {
  var t = {
    id: 'task-' + Math.random().toString(36).slice(2, 8),
    icon: '🆕',
    name: 'مهمة جديدة',
    role: 'reception',
    enabled: true,
    instructions: '',
    fields: [{ label: 'حقل جديد', type: 'text' }],
    payload: null
  };
  currentTasks().push(t);
  renderTaskList();
  selectTask(currentTasks().length - 1);
  renderStats();
}

/* ===== المعاينة الحية ===== */
function renderPreview(task) {
  var box = document.getElementById('livePreview');
  box.innerHTML = '';

  var card = document.createElement('div');
  card.className = 'form-card';
  card.innerHTML =
    '<h5>🧭 بيانات إلزامية — Schema</h5>' +
    '<div class="req-note">كل الحقول المعلّمة بـ * إلزامية — زر الإرسال يفتح تلقائياً عند الاكتمال</div>' +
    '<div class="form-progress"><i style="width:0%"></i></div>';

  for (var i = 0; i < task.fields.length; i++) {
    var f = task.fields[i];
    var wrap = document.createElement('div');
    wrap.className = 'field';
    var lbl = document.createElement('label');
    lbl.innerHTML = esc(f.label || '—') + ' <span class="star">*</span>';
    wrap.appendChild(lbl);
    var inp;
    if (f.type === 'select') {
      inp = document.createElement('select');
      var op = document.createElement('option');
      op.textContent = 'اختر...';
      inp.appendChild(op);
    } else if (f.type === 'textarea') {
      inp = document.createElement('textarea');
      inp.rows = 2;
    } else {
      inp = document.createElement('input');
      inp.type = 'text';
    }
    inp.disabled = true;
    wrap.appendChild(inp);
    card.appendChild(wrap);
  }

  var btn = document.createElement('button');
  btn.className = 'btn-primary form-submit';
  btn.disabled = true;
  btn.textContent = 'إرسال البيانات';
  card.appendChild(btn);

  box.appendChild(card);
}

/* ================= Employees ================= */
function renderEmployees() {
  var body = document.getElementById('empTableBody');
  body.innerHTML = '';
  var emps = ADMIN_LIVE ? L_EMPS : EMPLOYEES;

  for (var i = 0; i < emps.length; i++) {
    (function (emp) {
      var tr = document.createElement('tr');

      var tdName = document.createElement('td');
      tdName.textContent = emp.name + (ADMIN_LIVE ? ' (' + emp.username + ')' : '');

      var tdRole = document.createElement('td');
      var sel = document.createElement('select');
      for (var r in ROLES) {
        if (ROLES.hasOwnProperty(r)) {
          var op = document.createElement('option');
          op.value = r;
          op.textContent = ROLES[r];
          sel.appendChild(op);
        }
      }
      var opA = document.createElement('option');
      opA.value = 'admin'; opA.textContent = '⭐ أدمن';
      sel.appendChild(opA);
      sel.value = emp.role;
      sel.addEventListener('change', function () {
        emp.role = sel.value;
        if (ADMIN_LIVE) empUpdate({ id: emp.id, role: sel.value });
      });
      tdRole.appendChild(sel);

      var tdState = document.createElement('td');
      tdState.innerHTML = emp.active
        ? '<span class="pill on">مفعّل</span>'
        : '<span class="pill off">موقوف</span>';

      var tdAct = document.createElement('td');
      var btn = document.createElement('button');
      btn.className = 'chip-btn';
      btn.textContent = emp.active ? 'إيقاف' : 'تفعيل';
      btn.onclick = function () {
        emp.active = !emp.active;
        if (ADMIN_LIVE) empUpdate({ id: emp.id, active: emp.active ? 1 : 0 }, renderEmployees);
        else renderEmployees();
      };
      tdAct.appendChild(btn);

      if (ADMIN_LIVE) {
        var pw = document.createElement('button');
        pw.className = 'chip-btn';
        pw.textContent = '🔑';
        pw.title = 'تغيير كلمة المرور';
        pw.onclick = function () {
          var np = prompt('كلمة المرور الجديدة لـ ' + emp.name + ' (8 أحرف على الأقل):');
          if (np && np.length >= 8) empUpdate({ id: emp.id, password: np }, function () { alert('تم تغيير كلمة المرور ✔'); });
          else if (np) alert('قصيرة جداً — 8 أحرف على الأقل');
        };
        tdAct.appendChild(document.createTextNode(' '));
        tdAct.appendChild(pw);
      }

      tr.appendChild(tdName);
      tr.appendChild(tdRole);
      tr.appendChild(tdState);
      tr.appendChild(tdAct);
      body.appendChild(tr);
    })(emps[i]);
  }
  renderStats();
}

function empUpdate(fields, cb) {
  fields.action = 'update';
  fetch('/api/employees', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(fields)
  })
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (!d.ok) { alert('خطأ: ' + d.error); loadEmployees(); }
      else if (cb) cb();
    })
    .catch(function () { alert('تعذر الاتصال بالخادم'); });
}

/* نموذج إضافة موظف (يُبنى مرة واحدة في الوضع الحي) */
function buildEmpForm() {
  var view = document.getElementById('view-employees');
  var form = document.createElement('div');
  form.className = 'task-builder';
  form.style.marginBottom = '16px';
  form.innerHTML =
    '<h4 class="sec-title sm">＋ إضافة موظف جديد</h4>' +
    '<div class="b-row" style="grid-template-columns:1fr 1fr">' +
    '<div class="b-field"><label>الاسم الكامل</label><input type="text" id="neName"></div>' +
    '<div class="b-field"><label>اسم المستخدم (إنجليزي)</label><input type="text" id="neUser"></div>' +
    '</div>' +
    '<div class="b-row" style="grid-template-columns:1fr 1fr">' +
    '<div class="b-field"><label>كلمة المرور (8+ أحرف)</label><input type="text" id="nePass"></div>' +
    '<div class="b-field"><label>القسم</label><select id="neRole"></select></div>' +
    '</div>' +
    '<button class="btn-primary slim" id="neBtn">إنشاء الحساب</button> ' +
    '<small id="neMsg" style="color:var(--text-2)"></small>';
  view.insertBefore(form, view.querySelector('.emp-table'));

  var sel = form.querySelector('#neRole');
  for (var r in ROLES) {
    if (ROLES.hasOwnProperty(r)) {
      var op = document.createElement('option');
      op.value = r; op.textContent = ROLES[r];
      sel.appendChild(op);
    }
  }
  var opA = document.createElement('option');
  opA.value = 'admin'; opA.textContent = '⭐ أدمن';
  sel.appendChild(opA);

  var ERR = {
    name_short: 'الاسم قصير', bad_username: 'اسم المستخدم: 3–30 حرفاً إنجليزياً/أرقام فقط',
    password_short: 'كلمة المرور 8 أحرف على الأقل', bad_role: 'اختر قسماً',
    username_taken: 'اسم المستخدم محجوز — اختر غيره'
  };

  form.querySelector('#neBtn').addEventListener('click', function () {
    var msg = form.querySelector('#neMsg');
    msg.textContent = 'جارٍ الإنشاء...';
    fetch('/api/employees', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'create',
        name: form.querySelector('#neName').value.trim(),
        username: form.querySelector('#neUser').value.trim(),
        password: form.querySelector('#nePass').value,
        role: sel.value
      })
    })
      .then(function (r) { return r.json(); })
      .then(function (d) {
        if (d.ok) {
          msg.textContent = '✔ أُنشئ الحساب — سلّم بيانات الدخول للموظف بأمان';
          form.querySelector('#neName').value = '';
          form.querySelector('#neUser').value = '';
          form.querySelector('#nePass').value = '';
          loadEmployees();
        } else {
          msg.textContent = '✖ ' + (ERR[d.error] || d.error);
        }
      })
      .catch(function () { msg.textContent = '✖ تعذر الاتصال'; });
  });
}
/* ================= Review queue — دورة المخرَج (المرحلة 4) ================= */
var L_LIFECYCLE = null;

function renderLifecycle() {
  var box = document.getElementById('lcStatus');
  if (!box) return;
  if (!ADMIN_LIVE || !L_LIFECYCLE) { box.textContent = '🔌 وضع تجريبي — لوحة الدورة تعمل في الوضع الحي فقط'; return; }
  var lc = L_LIFECYCLE;
  var html = '';
  if (lc.phase === 'pre-golive') {
    html = '🟠 <b>ما قبل Go-Live</b> — الوضع انتقالي إلزامياً: كل مخرَج يمر عليك (لا اعتماد آلي).';
    document.getElementById('goLiveBtn').style.display = 'inline-block';
  } else if (lc.phase === 'transition') {
    html = '🟡 <b>الفترة الانتقالية سارية</b> — متبقٍ <b>' + lc.daysLeft + '</b> يوماً من ' + lc.days + '. كل مخرَج → مراجعتك إلزامياً.';
  } else {
    html = '🟢 <b>ما بعد الفترة الانتقالية</b> — critical يمر عليك دائماً · العادي يُعتمد آلياً مع عيّنة رقابية <b>' + Math.round(lc.rate * 100) + '%</b>.';
  }
  box.innerHTML = html;
  var rw = document.getElementById('rateWrap');
  rw.style.display = 'inline-block';
  var ri = document.getElementById('rateInp');
  if (ri && !ri.value) ri.value = lc.rate;
}

function renderReview() {
  var list = document.getElementById('reviewList');
  list.innerHTML = '';
  var items = ADMIN_LIVE ? L_OUTS : REVIEW_QUEUE;
  var pending = 0;

  for (var i = 0; i < items.length; i++) {
    (function (item) {
      var st = ADMIN_LIVE ? item.status : (item.state === 'ok' ? 'Approved' : (item.state === 'back' ? 'Rejected' : (!item.state ? 'Pending-Review' : 'Pending-Review')));
      var isPending = (st === 'Pending-Review');
      if (isPending) pending++;

      var card = document.createElement('div');
      card.className = 'review-card' + (isPending ? '' : ' review-done');

      var stateHtml = '';
      if (st === 'Approved') stateHtml = '<span class="review-state ok">✔ Approved' + (item.reviewed_by ? ' · ' + esc(item.reviewed_by) : '') + '</span>';
      if (st === 'Rejected') stateHtml = '<span class="review-state back">✖ Rejected — ' + esc(item.reject_reason || '') + '</span>';
      if (st === 'Draft') stateHtml = '<span class="review-state">📝 Draft (لم يُرسَل بعد)</span>';

      var critHtml = '';
      if (ADMIN_LIVE && item.criticality === 'critical') {
        critHtml = ' <span class="review-state back" title="' + esc(item.crit_reasons || '') + '">🔴 critical' + (item.crit_reasons ? ' — ' + esc(item.crit_reasons) : '') + '</span>';
      }
      if (ADMIN_LIVE && item.sampled) critHtml += ' <span class="review-state">🎲 عيّنة رقابية</span>';

      var emp = ADMIN_LIVE ? item.emp_name : item.emp;
      var taskLbl = ADMIN_LIVE ? item.task_id : item.task;
      var time = ADMIN_LIVE ? (item.created_at || '') : item.time;

      card.innerHTML =
        '<div class="review-meta"><b>' + esc(emp) + '</b> · ' + esc(taskLbl) + ' · ' + esc(time) + ' ' + stateHtml + critHtml + '</div>' +
        '<div class="review-output">' + esc(ADMIN_LIVE ? item.content : item.output).replace(/\n/g, '<br>') + '</div>';

      if (isPending) {
        var actions = document.createElement('div');
        actions.className = 'review-actions';

        var ok = document.createElement('button');
        ok.className = 'btn-ok';
        ok.textContent = '✔ اعتماد';
        ok.onclick = function () { decide(item, 'Approved'); };

        var back = document.createElement('button');
        back.className = 'btn-back';
        back.textContent = '✖ رفض (بسبب)';
        back.onclick = function () { decide(item, 'Rejected'); };

        actions.appendChild(ok);
        actions.appendChild(back);
        card.appendChild(actions);
      }
      list.appendChild(card);
    })(items[i]);
  }

  if (items.length === 0) {
    list.innerHTML = '<div class="empty-note">لا مخرجات بانتظار المراجعة 🎉</div>';
  }

  var badge = document.getElementById('reviewBadge');
  badge.textContent = pending;
  badge.style.display = pending ? 'inline-block' : 'none';
  var sp = document.getElementById('statPending');
  if (sp) sp.textContent = pending;
  renderLifecycle();
}

function decide(item, decision) {
  if (ADMIN_LIVE) {
    var reason = '';
    if (decision === 'Rejected') {
      reason = (prompt('سبب الرفض (إلزامي — يصل للموظف):') || '').trim();
      if (!reason) { alert('الرفض بلا سبب غير ممكن.'); return; }
    }
    fetch('/api/outputs', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'decide', id: item.id, decision: decision, reason: reason })
    })
      .then(function (r) { return r.json(); })
      .then(function (d) {
        if (d.ok) { loadOutputs(); }
        else alert('خطأ: ' + (d.msg || d.error));
      })
      .catch(function () { alert('تعذر الاتصال بالخادم'); });
    return;
  }
  item.state = (decision === 'Approved') ? 'ok' : 'back';
  renderReview();
}

/* أزرار لوحة الدورة */
document.addEventListener('DOMContentLoaded', function () {
  var gl = document.getElementById('goLiveBtn');
  if (gl) gl.addEventListener('click', function () {
    if (!confirm('🚀 تفعيل Go-Live الآن؟\n\nيبدأ عدّاد الفترة الانتقالية (كل مخرَج → مراجعتك إلزامياً طوالها). لا يمكن التراجع.')) return;
    fetch('/api/outputs', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'golive' })
    }).then(function (r) { return r.json(); })
      .then(function (d) { if (d.ok) { alert('✅ Go-Live: ' + d.go_live_date); loadOutputs(); } else alert('خطأ: ' + (d.msg || d.error)); });
  });
  var rb = document.getElementById('rateBtn');
  if (rb) rb.addEventListener('click', function () {
    var v = document.getElementById('rateInp').value.trim();
    fetch('/api/outputs', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'set_setting', key: 'normal_sample_rate', value: v })
    }).then(function (r) { return r.json(); })
      .then(function (d) { if (d.ok) { alert('✅ حُفظت النسبة'); loadOutputs(); } else alert('خطأ: ' + (d.msg || d.error)); });
  });
});

/* ================= تحميل البيانات الحية ================= */
function loadTasks() {
  return fetch('/api/admin-tasks')
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (d.ok) { L_TASKS = d.tasks.map(dbTaskToEditor); renderTaskList(); renderStats(); }
    });
}
function loadEmployees() {
  return fetch('/api/employees')
    .then(function (r) { return r.json(); })
    .then(function (d) { if (d.ok) { L_EMPS = d.employees; renderEmployees(); } });
}
function loadOutputs() {
  return fetch('/api/outputs')
    .then(function (r) { return r.json(); })
    .then(function (d) { if (d.ok) { L_OUTS = d.outputs; L_LIFECYCLE = d.lifecycle || null; renderReview(); } });
}

/* ============================================================
   🧠 ملفات العقول — المرحلة 1 (الترويسة-9)
   ============================================================ */
var MF_SCOPE = 'active';

function mfLoad() {
  if (!ADMIN_LIVE) {
    document.getElementById('mfList').innerHTML = '<div class="empty-note">تعمل هذه الشاشة بعد الاتصال بقاعدة البيانات (الوضع الحي)</div>';
    return;
  }
  var url = '/api/minds-files' + (MF_SCOPE === 'archive' ? '?scope=archive' : '');
  fetch(url)
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (!d.ok) { document.getElementById('mfList').innerHTML = '<div class="empty-note">خطأ: ' + esc(d.error || '') + ' — هل نُفِّذت سكيما المرحلة 1 في القاعدة؟</div>'; return; }
      mfRender(d.files || []);
    })
    .catch(function () { document.getElementById('mfList').innerHTML = '<div class="empty-note">تعذر الاتصال</div>'; });
}

function mfRender(files) {
  var box = document.getElementById('mfList');
  if (!files.length) {
    box.innerHTML = '<div class="empty-note">' + (MF_SCOPE === 'archive' ? 'الأرشيف فارغ' : 'لا ملفات نشطة بعد') + '</div>';
    return;
  }
  var html = '<table class="emp-table"><thead><tr><th>الملف</th><th>الطبقة</th><th>يورَّث إلى</th><th>الحساسية</th><th>القرار الأم</th><th>الحالة</th><th></th></tr></thead><tbody>';
  for (var i = 0; i < files.length; i++) {
    var f = files[i];
    html += '<tr>' +
      '<td style="max-width:260px;overflow:hidden;text-overflow:ellipsis" title="' + esc(f.name) + '">' + esc(f.name) + '<br><small style="color:var(--text-2)">' + esc(f.stage) + ' ' + esc(f.stage_version || '') + ' · ' + esc(f.updated_at || '') + '</small></td>' +
      '<td>' + esc(f.layer) + '</td>' +
      '<td>' + esc(f.inherits_to) + '</td>' +
      '<td>' + esc(f.surface_sensitivity) + '</td>' +
      '<td>' + esc(f.parent_decision) + '</td>' +
      '<td>' + (f.status === 'Active' ? '<span class="pill on">Active</span>' : '<span class="pill off">' + esc(f.status) + '</span>') + '</td>' +
      '<td>' + (f.status === 'Active'
        ? '<button class="chip-btn" onclick="mfSetStatus(\'' + f.id + '\',\'Superseded\')">🗄 Supersede</button> <button class="chip-btn" onclick="mfAutoLink(\'' + f.id + '\')" title="اشتقاق الربط من حقل يورَّث إلى">🕸 ربط تلقائي</button>'
        : '<button class="chip-btn" onclick="mfSetStatus(\'' + f.id + '\',\'Active\')">↩ تفعيل</button>') + '</td>' +
      '</tr>';
  }
  html += '</tbody></table>';
  box.innerHTML = html;
}

function mfSetStatus(id, status) {
  fetch('/api/minds-files', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'update_header', id: id, status: status })
  })
    .then(function (r) { return r.json(); })
    .then(function (d) { if (d.ok) mfLoad(); else alert('خطأ: ' + (d.msg || d.error)); })
    .catch(function () { alert('تعذر الاتصال'); });
}

function mfCreate(gateOverride) {
  var msg = document.getElementById('mfMsg');
  msg.style.color = 'var(--text-2)';
  msg.textContent = 'جارٍ الإدخال...';
  var inheritsRaw = document.getElementById('mfInherits').value.trim();
  var supersedesRaw = document.getElementById('mfSupersedes').value.trim();
  fetch('/api/minds-files', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      action: 'create',
      gate_override: !!gateOverride,
      name: document.getElementById('mfName').value.trim(),
      stage: document.getElementById('mfStage').value,
      stage_version: document.getElementById('mfStageV').value.trim() || '-',
      status: document.getElementById('mfStatus').value,
      supersedes: supersedesRaw ? supersedesRaw.split('،').join(',').split(',').map(function (s) { return s.trim(); }).filter(Boolean) : '',
      layer: document.getElementById('mfLayer').value.trim(),
      inherits_to: inheritsRaw ? inheritsRaw.split('،').join(',').split(',').map(function (s) { return s.trim(); }).filter(Boolean) : '',
      surface_sensitivity: document.getElementById('mfSens').value,
      parent_decision: document.getElementById('mfDecision').value.trim(),
      content: document.getElementById('mfContent').value
    })
  })
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (d.ok) {
        msg.style.color = 'var(--ok)';
        msg.textContent = '✔ أُدخل الملف' + (d.superseded ? ' · وتحوّل ' + d.superseded + ' ملف قديم إلى Superseded آلياً' : '');
        document.getElementById('mfName').value = '';
        document.getElementById('mfContent').value = '';
        MF_SCOPE = 'active';
        mfLoad();
      } else if (d.error === 'gate_blocked') {
        msg.style.color = 'var(--danger)';
        msg.textContent = '🔒 ' + d.msg;
        var list = d.hits.map(function (h) { return '• ' + h.type + ': ' + h.masked; }).join('\n');
        if (confirm('🔒 فلتر بوابة GOV-SEC علّق الرفع واصطاد:\n\n' + list +
          '\n\nهل تؤكد — بصفتك المالك — أن هذه ليست أسراراً حقيقية (مثل تواريخ في أسماء الملفات أو مصطلحات واردة في نص معتمد)؟\n\nالتأكيد يُسجَّل باسمك في سجل الوصول.')) {
          mfCreate(true);
        } else {
          incidentsLoad();
        }
      } else {
        msg.style.color = 'var(--danger)';
        msg.textContent = '✖ ' + (d.msg || d.error);
      }
    })
    .catch(function () { msg.style.color = 'var(--danger)'; msg.textContent = '✖ تعذر الاتصال'; });
}

/* 🚨 حوادث بوابة GOV-SEC (المرحلة 3) */
function incidentsLoad() {
  fetch('/api/minds-files?incidents=1')
    .then(function (r) { return r.json(); })
    .then(function (d) {
      var box = document.getElementById('incList');
      if (!d.ok) { box.innerHTML = '<div class="empty-note">خطأ: ' + esc(d.error || '') + ' — هل نُفِّذت سكيما المرحلة 3؟</div>'; return; }
      if (!d.incidents.length) { box.innerHTML = '<div class="empty-note">لا حوادث مسجَّلة 🎉</div>'; return; }
      var html = '<table class="emp-table"><thead><tr><th>#</th><th>الحادثة</th><th>متى (UTC)</th><th>الحالة</th><th></th></tr></thead><tbody>';
      for (var i = 0; i < d.incidents.length; i++) {
        var c = d.incidents[i];
        html += '<tr><td>' + c.id + '</td>' +
          '<td style="max-width:380px">' + esc(c.what_entered) + (c.remediation ? '<br><small style="color:var(--text-2)">المعالجة: ' + esc(c.remediation) + '</small>' : '') + '</td>' +
          '<td>' + esc(c.created_at || '') + '</td>' +
          '<td>' + (c.resolved ? '<span class="pill on">مُعالَجة</span>' : '<span class="pill off">مفتوحة</span>') + '</td>' +
          '<td>' + (c.resolved ? '' : '<button class="chip-btn" onclick="incResolve(' + c.id + ')">✔ معالجة</button>') + '</td></tr>';
      }
      html += '</tbody></table>';
      box.innerHTML = html;
    })
    .catch(function () {});
}

function incResolve(id) {
  var rem = prompt('قرار المعالجة (مثال: إنذار كاذب — تواريخ في اسم الملف · أو: سر حقيقي — تم تدويره):');
  if (!rem) return;
  fetch('/api/minds-files', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'resolve_incident', id: id, remediation: rem })
  })
    .then(function (r) { return r.json(); })
    .then(function (d) { if (d.ok) incidentsLoad(); else alert('خطأ: ' + d.error); })
    .catch(function () { alert('تعذر الاتصال'); });
}

/* ============================================================
   🔒 المرحلة 3: Checklist بوابة GOV-SEC (م5 — لا يُتخطى)
   5 أسئلة إلزامية قبل أي إدخال — «نعم» على أيٍّ منها = منع.
   ============================================================ */
var GATE_QUESTIONS = [
  'هل يحتوي المحتوى رقم ترخيص (ممارس · منشأة · جهاز)؟',
  'هل يحتوي رقم سجل تجاري أو رسمي؟',
  'هل يحتوي رقم اعتماد؟',
  'هل يحتوي أسماء أفراد عائلة أو نسب ملكية؟',
  'هل يحتوي سراً تقنياً (كلمة مرور · API Key · Token)؟'
];

function gateChecklist(onPass) {
  var overlay = document.createElement('div');
  overlay.style.cssText = 'position:fixed;inset:0;background:rgba(9,55,52,.55);z-index:100;display:flex;align-items:center;justify-content:center;padding:16px';
  var card = document.createElement('div');
  card.className = 'task-builder';
  card.style.cssText = 'max-width:520px;width:100%;max-height:90vh;overflow-y:auto';
  var html = '<h4 class="sec-title sm">🔒 فحص بوابة GOV-SEC — إلزامي قبل الإدخال</h4>' +
    '<p class="view-sub">أجب على الأسئلة الخمسة — أي «نعم» يعني أن هذا المحتوى مكانه السجل المغلق خارج المنظومة، لا هنا.</p>';
  for (var i = 0; i < GATE_QUESTIONS.length; i++) {
    html += '<div class="b-field" style="margin-bottom:10px"><label>' + (i + 1) + '· ' + GATE_QUESTIONS[i] + '</label>' +
      '<div><label style="margin-inline-end:18px"><input type="radio" name="gq' + i + '" value="no"> لا</label>' +
      '<label><input type="radio" name="gq' + i + '" value="yes"> نعم</label></div></div>';
  }
  html += '<div id="gateMsg" style="color:var(--danger);font-size:12.5px;min-height:18px;margin-bottom:8px"></div>' +
    '<div class="builder-actions"><button class="btn-primary slim" id="gateOk" disabled>تأكيد الإدخال</button>' +
    '<button class="chip-btn" id="gateCancel">إلغاء الرفع</button></div>';
  card.innerHTML = html;
  overlay.appendChild(card);
  document.body.appendChild(overlay);

  function check() {
    var allNo = true, anyYes = false, answered = 0;
    for (var i = 0; i < GATE_QUESTIONS.length; i++) {
      var sel = card.querySelector('input[name="gq' + i + '"]:checked');
      if (sel) { answered++; if (sel.value === 'yes') anyYes = true; }
      if (!sel || sel.value !== 'no') allNo = false;
    }
    var msg = card.querySelector('#gateMsg');
    var ok = card.querySelector('#gateOk');
    if (anyYes) {
      msg.textContent = '🔒 ممنوع الإدخال — هذا المحتوى مكانه السجل المغلق خارج المنظومة (م5). ألغِ الرفع.';
      ok.disabled = true;
    } else {
      msg.textContent = '';
      ok.disabled = (answered < GATE_QUESTIONS.length);
    }
  }
  var radios = card.querySelectorAll('input[type="radio"]');
  for (var r = 0; r < radios.length; r++) radios[r].addEventListener('change', check);

  card.querySelector('#gateCancel').addEventListener('click', function () { document.body.removeChild(overlay); });
  card.querySelector('#gateOk').addEventListener('click', function () {
    document.body.removeChild(overlay);
    onPass();
  });
}

document.getElementById('mfCreateBtn').addEventListener('click', function () {
  if (!ADMIN_LIVE) { mfCreate(); return; }
  gateChecklist(function () { mfCreate(); });
});
document.getElementById('incBtn').addEventListener('click', incidentsLoad);

/* 📦 استيراد حزمة معتمدة (تحميل ملفات العقول) */
document.getElementById('bundleBtn').addEventListener('click', function () {
  var inp = document.getElementById('bundleFile');
  var msg = document.getElementById('bundleMsg');
  if (!inp.files || !inp.files.length) { msg.textContent = '✖ اختر ملف الحزمة (JSON) أولاً'; return; }

  var reader = new FileReader();
  reader.onload = function () {
    var bundle;
    try { bundle = JSON.parse(reader.result); } catch (e) { msg.textContent = '✖ ملف JSON غير سليم'; return; }
    if (!Array.isArray(bundle.files)) { msg.textContent = '✖ بنية الحزمة غير صحيحة'; return; }

    gateChecklist(function () {
      if (!confirm('📦 استيراد ' + bundle.files.length + ' ملفاً معتمداً.\n\nالفلتر سيصطاد كلمات تنظيمية واردة في نصوص الحوكمة نفسها (مثل «ترخيص») — تأكيدك يتجاوزها موثَّقاً باسمك لكل ملف.\n\nنتابع؟')) return;
      msg.textContent = '⏳ جارٍ الاستيراد...';
      fetch('/api/minds-files', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'import_bundle', gate_override: true, files: bundle.files, links: bundle.links || [] })
      })
        .then(function (r) { return r.json(); })
        .then(function (d) {
          if (!d.ok) { msg.textContent = '✖ ' + (d.msg || d.error); return; }
          var okN = d.report.filter(function (x) { return x.ok; }).length;
          var failN = d.report.length - okN;
          var lines = d.report.map(function (x) {
            return (x.ok ? '✔ ' : '✖ ') + x.name +
              (x.superseded ? ' · ألغى ' + x.superseded : '') +
              (x.linked && x.linked.length ? ' · رُبط: ' + x.linked.join('،') : '') +
              (x.msg ? ' — ' + x.msg : '');
          });
          if (d.links && d.links.length) {
            lines.push('— روابط الوراثة —');
            d.links.forEach(function (l) {
              lines.push((l.ok ? '✔ ' : '✖ ') + l.mind + ': رُبط ' + (l.linked || 0) + ' ملفاً قائماً' +
                (l.missing && l.missing.length ? ' · مفقود: ' + l.missing.join('،') : ''));
            });
          }
          msg.innerHTML = '<b>اكتمل: ' + okN + ' نجح · ' + failN + ' فشل</b><br>' + lines.map(esc).join('<br>');
          mfLoad(); mindsLoad(); incidentsLoad();
        })
        .catch(function () { msg.textContent = '✖ تعذر الاتصال'; });
    });
  };
  reader.readAsText(inp.files[0]);
});
document.getElementById('mfTabActive').addEventListener('click', function () { MF_SCOPE = 'active'; mfLoad(); });
document.getElementById('mfTabArchive').addEventListener('click', function () { MF_SCOPE = 'archive'; mfLoad(); });

/* ============================================================
   🕸 العقول والتوريث — المرحلة 2
   ============================================================ */
function mindsLoad() {
  if (!ADMIN_LIVE) return;
  fetch('/api/minds')
    .then(function (r) { return r.json(); })
    .then(function (d) {
      var box = document.getElementById('mindsList');
      if (!d.ok) { box.innerHTML = '<div class="empty-note">خطأ: ' + esc(d.error || '') + ' — هل نُفِّذت سكيما المرحلة 2؟</div>'; return; }
      if (!d.minds.length) { box.innerHTML = '<div class="empty-note">لا عقول بعد — أنشئ العقل المركزي أولاً (المعرّف: central)</div>'; return; }
      var html = '<table class="emp-table"><thead><tr><th>العقل</th><th>الطبقة</th><th>الأب</th><th>السطح</th><th>ملفات Active مربوطة</th><th></th></tr></thead><tbody>';
      for (var i = 0; i < d.minds.length; i++) {
        var m = d.minds[i];
        html += '<tr>' +
          '<td><b>' + esc(m.id) + '</b><br><small style="color:var(--text-2)">' + esc(m.name) + '</small></td>' +
          '<td>' + esc(m.layer) + '</td>' +
          '<td>' + esc(m.parent_mind_id || '—') + '</td>' +
          '<td>' + esc(m.surface) + '</td>' +
          '<td>' + m.active_files + '</td>' +
          '<td><button class="chip-btn" onclick="mindRead(\'' + esc(m.id) + '\')">📖 ماذا يقرأ؟</button></td>' +
          '</tr>';
      }
      html += '</tbody></table>';
      box.innerHTML = html;
    })
    .catch(function () {});
}

function mindCreate() {
  var msg = document.getElementById('mnMsg');
  msg.style.color = 'var(--text-2)';
  msg.textContent = 'جارٍ الإنشاء...';
  fetch('/api/minds', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      action: 'create_mind',
      id: document.getElementById('mnId').value.trim(),
      name: document.getElementById('mnName').value.trim(),
      layer: document.getElementById('mnLayer').value,
      parent_mind_id: document.getElementById('mnParent').value.trim(),
      surface: document.getElementById('mnSurface').value.trim() || '-'
    })
  })
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (d.ok) {
        msg.style.color = 'var(--ok)';
        msg.textContent = '✔ أُنشئ العقل ' + d.id;
        document.getElementById('mnId').value = '';
        document.getElementById('mnName').value = '';
        mindsLoad();
      } else {
        msg.style.color = 'var(--danger)';
        msg.textContent = '✖ ' + (d.msg || d.error);
      }
    })
    .catch(function () { msg.style.color = 'var(--danger)'; msg.textContent = '✖ تعذر الاتصال'; });
}

function mfAutoLink(fileId) {
  fetch('/api/minds', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'auto_link', file_id: fileId })
  })
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (d.ok) {
        alert(d.linked.length
          ? '✔ رُبط الملف بـ ' + d.linked.length + ' عقل: ' + d.linked.join(' · ')
          : 'لا عقول مطابقة لحقل «يورَّث إلى» — أنشئ العقول أولاً أو الحقل = -');
        mindsLoad();
      } else alert('خطأ: ' + (d.msg || d.error));
    })
    .catch(function () { alert('تعذر الاتصال'); });
}

function mindRead(mindId) {
  fetch('/api/minds?read=' + encodeURIComponent(mindId))
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (!d.ok) { alert('خطأ: ' + (d.msg || d.error)); return; }
      if (!d.files.length) { alert('العقل «' + mindId + '» لا يقرأ أي ملف حالياً (لا مربوط Active)'); return; }
      var names = d.files.map(function (f) { return '• ' + f.name; });
      alert('📖 العقل «' + mindId + '» يقرأ الآن ' + d.files.length + ' ملفاً:\n\n' + names.join('\n') + '\n\n(سُجّلت هذه القراءة في سجل الوصول)');
    })
    .catch(function () { alert('تعذر الاتصال'); });
}

function logsLoad() {
  fetch('/api/minds?logs=1')
    .then(function (r) { return r.json(); })
    .then(function (d) {
      var box = document.getElementById('alList');
      if (!d.ok) { box.innerHTML = '<div class="empty-note">خطأ: ' + esc(d.error || '') + '</div>'; return; }
      if (!d.logs.length) { box.innerHTML = '<div class="empty-note">لا قراءات مسجَّلة بعد</div>'; return; }
      var html = '<table class="emp-table"><thead><tr><th>#</th><th>العقل</th><th>الفاعل</th><th>الملف</th><th>العملية</th><th>متى (UTC)</th></tr></thead><tbody>';
      for (var i = 0; i < d.logs.length; i++) {
        var l = d.logs[i];
        html += '<tr><td>' + l.id + '</td><td>' + esc(l.mind_id || '—') + '</td><td>' + esc(l.actor || '—') + '</td><td style="max-width:220px;overflow:hidden;text-overflow:ellipsis">' + esc(l.file_name || l.file_id || '—') + '</td><td>' + esc(l.action) + '</td><td>' + esc(l.at) + '</td></tr>';
      }
      html += '</tbody></table>';
      box.innerHTML = html;
    })
    .catch(function () {});
}

document.getElementById('mnCreateBtn').addEventListener('click', mindCreate);
document.getElementById('alBtn').addEventListener('click', logsLoad);

/* ================= 📱 Burger menu ================= */
function setSidebar(open) {
  var aside = document.querySelector('.admin-side');
  var scrim = document.getElementById('scrim');
  if (open) { aside.classList.add('open'); scrim.classList.add('show'); }
  else { aside.classList.remove('open'); scrim.classList.remove('show'); }
}
document.getElementById('burgerBtn').addEventListener('click', function () {
  var aside = document.querySelector('.admin-side');
  setSidebar(!aside.classList.contains('open'));
});
document.getElementById('scrim').addEventListener('click', function () { setSidebar(false); });

/* ================= Event bindings ================= */
var navBtns = document.querySelectorAll('.nav-item');
for (var n = 0; n < navBtns.length; n++) {
  (function (btn) {
    btn.addEventListener('click', function () {
      switchView(btn.getAttribute('data-view'));
      setSidebar(false);
    });
  })(navBtns[n]);
}
document.getElementById('themeBtn').addEventListener('click', toggleTheme);
document.getElementById('newTaskAdminBtn').addEventListener('click', newTask);
document.getElementById('addFieldBtn').addEventListener('click', addField);
document.getElementById('saveTaskBtn').addEventListener('click', saveTask);
document.getElementById('disableTaskBtn').addEventListener('click', toggleTaskEnabled);
document.getElementById('addEmpBtn').addEventListener('click', function () {
  if (!ADMIN_LIVE) {
    EMPLOYEES.push({ name: 'موظف تجريبي ' + (EMPLOYEES.length + 1), role: 'reception', active: true });
    renderEmployees();
  } else {
    window.scrollTo(0, 0);
  }
});

/* ================= Init: اكتشاف الوضع + حارس الدخول ================= */
function initDemo() {
  renderActivity();
  renderTaskList();
  renderEmployees();
  renderReview();
  renderStats();
}

fetch('/api/me')
  .then(function (r) { return r.json(); })
  .then(function (d) {
    if (!d.live) { initDemo(); return; }
    /* حارس: القاعدة حية → لا دخول للوحة إلا لأدمن مسجَّل */
    if (!d.user || d.user.role !== 'admin') {
      window.location.href = '../index.html';
      return;
    }
    ADMIN_LIVE = true;
    var banner = document.querySelector('.demo-banner');
    if (banner) {
      banner.innerHTML = '✅ متصل بقاعدة البيانات — كل التعديلات هنا <b>تُحفظ فعلياً</b> · مرحباً ' + esc(d.user.name);
    }
    document.getElementById('addEmpBtn').style.display = 'none';
    buildEmpForm();
    renderActivity();
    loadTasks();
    loadEmployees();
    loadOutputs();
    mfLoad();
    mindsLoad();
  })
  .catch(initDemo);
